package("spandsp")
    set_homepage("https://github.com/freeswitch/spandsp")
    set_description("SpanDSP is a low-level signal processing library that modulates and demodulates signals commonly used in telephony, such as the \"noise\" generated by a fax modem or DTMF touchpad.")

    add_urls("https://github.com/freeswitch/spandsp.git")
    add_urls("git@code.elkpi.com:third_party/spandsp.git")
    add_versions("2022.01.27", "e59ca8fb8b1591e626e6a12fdc60a2ebe83435ed")

    add_deps("autoconf", "automake", "libtool")
    add_deps("libjpeg-turbo", "libtiff", "zlib", "libffi")

    on_install(function (package)
        local configs = {}
        local cflags = {}
        local ldflags = {}

        table.insert(configs, "--enable-shared=" .. (package:config("shared") and "yes" or "no"))
        if package:debug() then
            table.insert(configs, "--enable-debug")
        end
        if package:is_plat("linux") and package:config("pic") ~= false then
            table.insert(configs, "--with-pic")
        end

        for _, dep in ipairs(package:orderdeps()) do
            local fetchinfo = dep:fetch()
            if fetchinfo then
                for _, includedir in ipairs(fetchinfo.includedirs or fetchinfo.sysincludedirs) do
                    table.insert(cflags, "-I" .. includedir)
                end
                for _, linkdir in ipairs(fetchinfo.linkdirs) do
                    table.insert(ldflags, "-L" .. linkdir)
                end
                for _, link in ipairs(fetchinfo.links) do
                    table.insert(ldflags, "-l" .. link)
                end
            end
        end

        import("package.tools.autoconf").install(package, configs, {cflags = cflags, ldflags = ldflags})
    end)

    on_test(function (package)
        assert(package:has_cfuncs("span_alloc", {includes = "spandsp.h"}))
    end)
